# Generated by Django 5.1 on 2026-07-30 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Harian'), ('weekly', 'Mingguan'), ('biweekly', '2 Mingguan'), ('monthly', 'Bulanan')], max_length=20)),
                ('interval', models.IntegerField(default=1)),
                ('days_of_week', models.CharField(blank=True, help_text='Contoh: 0,2,4 (Senin=0, Minggu=6)', max_length=30)),
                ('purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to='bookings.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.recurringpattern'),
        ),
    ]
