# Generated by Django 5.1 on 2026-08-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.TextField(blank=True, default=''),
        ),
    ]
