# Generated by Django 5.1 on 2026-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('no_show', 'No Show'), ('expired', 'Expired')], default='confirmed', max_length=20),
        ),
    ]
